import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <nav className="flex justify-between items-center px-8 py-6 border-b border-gray-200 dark:border-gray-800">
      <div className="flex items-center gap-2">
        <Image src="/next.svg" alt="Logo" width={40} height={40} />
        <span className="text-xl font-bold tracking-tight">Your Business</span>
      </div>
      <div className="flex gap-6 text-sm font-medium">
        <Link href="/" className="hover:underline">Home</Link>
        <Link href="/about" className="hover:underline">About</Link>
        <Link href="/products" className="hover:underline">Products</Link>
        <Link href="/blog" className="hover:underline">Blog</Link>
        <Link href="/contact" className="hover:underline">Contact</Link>
      </div>
    </nav>
  );
}

function Footer() {
  return (
    <footer className="py-8 text-center text-gray-500 text-sm border-t border-gray-100 dark:border-gray-800">
      &copy; {new Date().getFullYear()} Your Business. All rights reserved.
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col font-[family-name:var(--font-geist-sans)] bg-white text-black dark:bg-black dark:text-white">
          <Navbar />
          <main className="flex-1 flex flex-col">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
